name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pointodo-client
          build-args: 
            VITE_SERVER_HOST: ${{ secrets.VITE_SERVER_HOST }}

#       - name: Pull and restart Docker Container
#         uses: appleboy/ssh-action@master
#         with:
#           key: ${{ secrets.SSH_KEY }}
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USER }}
#           script: |
#             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_repo
#             docker stop my_repo
#             docker run -d --rm --name my_repo -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my_repo
