name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          script: |
            git config --global --add safe.directory /home/ubuntu/Pointodo-FE
            git config --global user.name "KubrickCode"
            git config --global user.email "kubrickcode@gmail.com"
            cd /home/ubuntu/Pointodo-FE
            git pull origin main
            /root/.nvm/versions/node/v18.17.1/bin/yarn install --immutable --immutable-cache --check-cache
            /root/.nvm/versions/node/v18.17.1/bin/yarn build
